### ISSUE TITLE
Lost with several CSS files

### ISSUE THREAD

**Issue by lionel-m** [corysimmons/lost#12]
Hi,

I use `lost` in several CSS files (using Gulp). In this context, the following code is written in each file:

```CSS
.container {
  max-width: 1000px;
  margin-right: auto;
  margin-left: auto;
  padding-left: 0;
  padding-right: 0;
}
.row {
  *zoom: 1;
  margin-left: -15px;
  margin-right: -15px;
}
.row:before,
.row:after {
  content: '';
  display: table;
}
.row:after {
  clear: both;
}
.container {
  max-width: 1000px;
  margin-right: auto;
  margin-left: auto;
  padding-left: 0;
  padding-right: 0;
}
.row {
  *zoom: 1;
  margin-left: -15px;
  margin-right: -15px;
}
.row:before,
.row:after {
  content: '';
  display: table;
}
.row:after {
  clear: both;
}
```
Would it be possible to have an option to write or not this part of the code (or another solution...)? In order to write only this code in one file.

Thanks
