### ISSUE TITLE
lost-align not working correctly on IE9

### ISSUE THREAD

**Issue by soenkekluth** [corysimmons/lost#125]
as you can see on the demo page "lost-align" is not working as aspected. vertical and horizontal centering is the problem.
http://corysimmons.github.io/lost/

![2015-05-20 12 58 53 pm](https://cloud.githubusercontent.com/assets/201338/7724254/5cf8528c-fef0-11e4-8203-682223a3f5e3.png)
tested with browserstack on win7

**Comment by corysimmons** [comment]
Is this with Flexbox?

**Comment by soenkekluth** [comment]
nope without. flexbox doesn't work at all.

**Comment by corysimmons** [comment]
Thanks for reporting this. I'll check into it soon.

**Comment by dmitrykiselyov** [comment]
IE9 doesn't support 3D transforms, instead, we can use 2D.
`transform: translate(-50%, -50%);`

```css
section:nth-of-type(4) > * {
    position: absolute;
    top: 50%;
    right: auto;
    bottom: auto;
    left: 50%;
    -webkit-transform: translate(-50%, -50%);
    transform: translate(-50%, -50%);
}
```
