### ISSUE TITLE
grid not working properly in simple realistic usecase - jeet does the job

### ISSUE THREAD

**Issue by soenkekluth** [corysimmons/lost#132]
hey @corysimmons I've setup a simple example comparing lost and jeet in a pretty simple usecase you can see here:
https://rawgit.com/soenkekluth/lost-vs-jeet/master/index.html

![2015-06-02 10 57 46 am](https://cloud.githubusercontent.com/assets/201338/7932287/763a850e-0917-11e5-941e-8c910719ebc6.png)

html snippet for all cases:
```
<article>
  <h2>title</h2>
  <div class="row">
    <nav class="red"></nav>
    <div class="blue"></div>
    <section class="green"></section>
  </div>
</article>
```
scss / postcss:
```
.lost-1 {
  .row {
    lost-utility: clearfix;

    > nav,
    > div,
    > section {
      lost-column: 1/3;
    }
  }
}

.lost-2 {
  .row {
    lost-utility: clearfix;

    > nav,
    > div,
    > section {
      lost-column: 1.0/3.0;
    }
  }
}

.jeet {
  .row {
    @include cf;

    > nav,
    > div,
    > section {
      @include col(1 / 3);
    }
  }
}

```

did i miss something?
please feel free to test it yourself:
https://github.com/soenkekluth/lost-vs-jeet

**Comment by soenkekluth** [comment]
ps. if all elements where the same type, like divs this would work: 
```
>div {
lost-column: 1/3;
}
```

**Comment by corysimmons** [comment]
Lost automatically tries to do some stuff for you (maybe I shouldn't have made this automatic). It finds the `nth-child` and `last-child` of things.

This might be an issue where modifying the `cycle` param will help.

`lost-column: 1/3 0` for all the ones that deserve a gutter. `lost-column: 1/3` for the last one.

I'll look more into this later and consider changing the API to be more predictable.

**Comment by soenkekluth** [comment]
@corysimmons  ok i see. 
nth-child and last-child natively work independent from its type of element. if you have:
`div + div + div + nav + div` 
 css would match: 
`nav:nth-child(4){...}`
jeet does the job because its compiled like that through sass...

a workaround could be to add the same class to each element. but who wants workarounds right?
`nav.col + div.col + section.col` css: `.col { lost-column: 1/3 }` should work in theory. did not try...

but what about that other strange thing with floating values vs in values. as you can see `lost-column: 1/3` works different from `lost-column: 1.0/3.0`

**Comment by GreanMaster** [comment]
i found this issue too , hope @corysimmons fix this issue soon
i use like this for running my work
```
article
	lost-utility: clearfix
	> section
		lost-column: 1/3
	> div
		lost-column: 1/3
	> nav
		lost-column: 1/3
```
and use clean-css merge duplicate rule

thank for sharing @soenkekluth

**Comment by dmitrykiselyov** [comment]
That's why it is not working properly https://github.com/corysimmons/lost/pull/134 :smile: 

```css
.lost-1 .row > nav,
.lost-1 .row > div,
.lost-1 .row > section:nth-child(n) {
  float: left;
  margin-right: 30px;
  clear: none; 
}
```
**must be**
```css
.lost-1 .row > nav:nth-child(n),
.lost-1 .row > div:nth-child(n),
.lost-1 .row > section:nth-child(n) {
  float: left;
  margin-right: 30px;
  clear: none;
}
```

@soenkekluth 
> but what about that other strange thing with floating values vs int values. as you can see 
lost-column: 1/3 works different from lost-column: 1.0/3.0

The difference is that in the first case (.lost-1) the `clear: left` work, but not in the second(.lost-2)
Because `.lost-2 .row > section:nth-child(3.0n + 1)` 3.0  float value, must be an integer. 

**now will work the same**
```css
.lost-2 .row > section:nth-child(3n + 1) {
  clear: left;
}
```
