### ISSUE TITLE
Avoid repetition with clearfix

### ISSUE THREAD

**Issue by alebelcor** [corysimmons/lost#136]
if we have something like:

```css
.container {
  lost-utility: clearfix;
}
```

It outputs:

```css
.container {
  *zoom: 1;
}

.container:before {
  content: '';
  display: table;
}

.container:after {
  content: '';
  display: table;
  clear: both;
}
```

Which I think can be further compressed to avoid repetition like:

```css
.container {
  *zoom: 1;
}

.container:before,
.container:after {
  content: '';
  display: table;
}

.container:after {
  clear: both;
}
```

As suggested [here](http://nicolasgallagher.com/micro-clearfix-hack/).

Let me know what you think.

Thanks!
