### ISSUE TITLE
Clearfix : Affect all elements...

### ISSUE THREAD

**Issue by jslyonnais** [corysimmons/lost#143]
Little problem in here since I've update Lost on my current project.

It seems that the use of "lost-utility: clearfix;" in css may apply a :before on every elements in the html. 
Ex.:
```css
.mobilemenu__bottom { lost-utility: clearfix; }
```

Then in HTML I've (and on every elements):
```css
.footer__nav-contact:after, :before {
    content: '';
    display: table;
}
```

http://ibin.co/26Eiwj5c8M9g
