### ISSUE TITLE
add optional parameter to enable/disable initialization

### ISSUE THREAD

**Issue by microcipcip** [corysimmons/lost#19]
It would be nice if there was a parameter to enable/disable the initalization of the columns, this would decrease a lot the size of the stylesheet, expecially if you're trying to generate a custom grid (similar to bootstrap). See the example below, where the `@include column($init: true);` would simply output float and margins, the for loop would only output the width.
````
[class*="col-"] {  // init
    @include column($init: true);
}
@for $i from 1 through 12 {
    .col-#{$i} { 
        @include column(#{$i}/12, $init: false);
    }
}
@include media-query(min-width: 380px) {
    @for $i from 1 through 12 {
        .col-xs-#{$i} { 
            @include column(#{$i}/12, $init: false);
         }
    }
}
@include media-query(min-width: 480px) {
    @for $i from 1 through 12 {
        .col-md-#{$i} { 
            @include column(#{$i}/12, $init: false);
        }
    }
}
````

**Comment by corysimmons** [comment]
Right now the only initialization going on is `float: left`. Too much?

**Comment by corysimmons** [comment]
Jeez you're a picky crowd! :D

**Comment by corysimmons** [comment]
How's this? https://github.com/corysimmons/lost/commit/51323f6e5fa5b2615c2fd28367909423fca95906

**Comment by corysimmons** [comment]
Clever technique! Works great. Here's your output:

```scss
.container {
  max-width: 1000px;
  margin-right: auto;
  margin-left: auto;
  padding-left: 0;
  padding-right: 0; }

.row {
  *zoom: 1;
  margin-left: -15px;
  margin-right: -15px; }
  .row:before, .row:after {
    content: '';
    display: table; }
  .row:after {
    clear: both; }

[class*="col-"] {
  float: left;
  width: calc(100% * 1 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-1 {
  width: calc(100% * 1/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-2 {
  width: calc(100% * 2/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-3 {
  width: calc(100% * 3/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-4 {
  width: calc(100% * 4/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-5 {
  width: calc(100% * 5/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-6 {
  width: calc(100% * 6/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-7 {
  width: calc(100% * 7/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-8 {
  width: calc(100% * 8/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-9 {
  width: calc(100% * 9/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-10 {
  width: calc(100% * 10/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-11 {
  width: calc(100% * 11/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

.col-12 {
  width: calc(100% * 12/12 - 30px);
  margin-left: 15px;
  margin-right: 15px; }

@media (min-width: 380px) {
  .col-xs-1 {
    width: calc(100% * 1/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-2 {
    width: calc(100% * 2/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-3 {
    width: calc(100% * 3/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-4 {
    width: calc(100% * 4/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-5 {
    width: calc(100% * 5/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-6 {
    width: calc(100% * 6/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-7 {
    width: calc(100% * 7/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-8 {
    width: calc(100% * 8/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-9 {
    width: calc(100% * 9/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-10 {
    width: calc(100% * 10/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-11 {
    width: calc(100% * 11/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-xs-12 {
    width: calc(100% * 12/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; } }
@media (min-width: 480px) {
  .col-md-1 {
    width: calc(100% * 1/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-2 {
    width: calc(100% * 2/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-3 {
    width: calc(100% * 3/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-4 {
    width: calc(100% * 4/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-5 {
    width: calc(100% * 5/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-6 {
    width: calc(100% * 6/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-7 {
    width: calc(100% * 7/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-8 {
    width: calc(100% * 8/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-9 {
    width: calc(100% * 9/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-10 {
    width: calc(100% * 10/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-11 {
    width: calc(100% * 11/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; }

  .col-md-12 {
    width: calc(100% * 12/12 - 30px);
    margin-left: 15px;
    margin-right: 15px; } }
```
