### ISSUE TITLE
less - generated calc rule is invalid

### ISSUE THREAD

**Issue by rmoorman** [corysimmons/lost#90]
Hello,

I just tried lost grid for less and encountered a problem which causes the grid system to fail with less.

I created a small example repo which can be used to reproduce the problem over [here](https://github.com/rmoorman/lost-test). As you can see [at line 193 of the generated css](https://github.com/rmoorman/lost-test/blob/master/css/style.css#L193) the px is not added correctly to the calc rule which confuses my browser and causes it to skip the generated width rule.

The version of lostgrid used within the example repo is the latest from github. I was able to circumvent the problem for my current use-case by using `%a` instead of `%s` within the `.column` mixin like this:

````less
.column(@fraction: 1 of 1, @cycle: extract(@fraction, 3), @gut: @gutter, @flex: @flexbox) {
  @numerator: extract(@fraction, 1);
  @denominator: extract(@fraction, 3);
  @_fraction: e('@{numerator}/@{denominator}');
  & when (@gut = 0) {
    width: e(%('calc(99.999999% * %s)', @_fraction));
  }
  & when not (@gut = 0) {
    width: e(%('calc(99.99% * %s - (%a - %a * %s))', @_fraction, @gut, @gut, @_fraction));
  }
````

but I could imagine that the problem also exists within some of the other mixins.

If you have any further questions or you need something else regarding this issue don't hesitate to ask :-)

Best regards,
Rico Moorman
